--- #YAML:1.0
name: DateTime-HiRes
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0.17
  Time::HiRes: 1.50
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::HiRes:
    file: lib/DateTime/HiRes.pm
    version: 0.01
generated_by: Module::Build version 0.19
